config/routes.rb
Rails.application.routes.draw do

  devise_for :players
  root 'games#index'
  resources :games
  # post 'games/make_move', to: 'games#make_move', as: :make_move

end

app/models/game.rb
class Game < ActiveRecord::Base
  require 'all_pieces'

  serialize :board, Board
  attr_accessor :game_board
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def current_games
    Game.where('player_1_id = ? OR player_2_id = ?', self.id, self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def push_move(game, turn, errors = nil)
    board_partial = render_to_string(partial: "games/board", locals: {game: @game, turn: @turn, errors: @errors })
    Pusher.trigger("opp-move", "move", board_partial)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_player!

  def index
    @games = current_player.current_games
    @games_to_watch = Game.all.reject { |game| @games.include?(game) }
  end

  def new
    @game = Game.new
    @players = Player.all.where("id != ?", current_player.id)
  end

  def create
    # fail
    @player1 = current_player
    @player2 = Player.find(game_params[:player_2_id])
    @game = Game.new({player_1_id: @player1.id, 
      player_2_id: @player2.id,
      board: Board.new,
      player_turn: 1,
      game_name: game_params[:game_name] })

    @turn = "white"
    @game.save
    redirect_to @game
  end

  def show
    # fail

    @game = Game.find(params[:id])
    @turn = @game.player_turn == 1 ? 'white' : 'black'
    @player1 = Player.find(@game.player_1_id)
    @player2 = Player.find(@game.player_2_id)
    @observer = (current_player == @player1 || current_player == @player2) ? false : true
    # fail
    # render partial: 'games/board', locals: { game: @game }
    render :show
  end

  def update
    @game = Game.find(params[:id])

    color = params[:color] == 'white' ? :white : :black
    from_pos = params[:from].map(&:to_i)
    to_pos = params[:to].map(&:to_i);
    # fail
    begin
      @game.board.move(from_pos, to_pos, color)
      @turn = params[:turn] == 'white' ? 'black' : 'white'
      @game.player_turn = @turn == 'white' ? 1 : 2
      @game.save
      push_move(@game, @turn)
    rescue Exception => e
      # fail
      @errors = [e.message]
      @game = Game.find(params[:id])
      @turn = params[:turn]
    end

    # if request.xhr?
    #   head :created
    # else
      render partial: 'games/board', locals: { game: @game, turn: @turn, errors: @errors }
    # end
  end

  def game_params
    params.require(:game).permit(:player_2_id, :game_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    return <<-HTML.html_safe
      <input type="hidden" name="authenticity_token" value="#{ form_authenticity_token }">
    HTML
  end

end

app/helpers/games_helper.rb
module GamesHelper

  def render_board
    html = ''
    @game.game_board.grid.reverse.each_with_index do |row, row_idx|
      row.each_with_index do |tile, col_idx|
        
        unless tile.nil?
          color = tile.color == :white ? 'white' : 'black'
          insert = "<div class='piece #{color}'>#{tile.to_s}</div>"
        else
          insert = ''
        end
        html << ""
      end
    end

    html
  end

end

app/views/games/_board.html.erb
  <h3 class="errors">
  <% if errors %>
    <% errors.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
  </h3>
<strong>It's <%= turn %>'s turn</strong>
<div class="board" data-current-turn="<%= turn %>">
<% game.board.grid.reverse.each_with_index do |row, row_idx| %>
  <% row.each_with_index do |tile,col_idx| %>
  
    <% css = (col_idx + row_idx).odd? ? "grey-background" : "white-background" %>
      <% (color = tile.color == :white ? 'white' : 'black') unless tile.nil?%>
      <article class="<%= css %> tile" data-row-id='<%= 7 - row_idx %>' data-col-id='<%= col_idx %>'>
      <% if tile %>
       <div class="piece <%= color %>" data-color="<%= tile.color %>"> 
        <%= tile.to_s %>
        </div>
      <% end %>
      </article>
  <% end %>
<% end %>
</div>

app/views/games/index.html.erb
<section class="main-content group">

  <article class="group">
    <h1>User's games</h1>
    <ul>
    <% @games.each do |game| %>
      <li><a href="<%= game_url(game) %>"><%= game.game_name %></a></li>
    <% end %>
    </ul>
  </article>

  <article class="group">
    <h1>Watch a Game</h1>
    <ul>
    <% @games_to_watch.each do |game| %>
      <li><a href="<%= game_url(game) %>"><%= game.game_name %></a></li>
    <% end %>
    </ul>
  </article>
</section>

app/views/games/new.html.erb
<h1>Create New Game</h1>
<form action="<%= games_url %>" method="post">
  <%= auth_token %>
  <div class="input">
  <label for="game_name">Game Name</label>
    <input id="game_name" type="text" name="game[game_name]" value="">
  </div>

  <div class="select">
  <label for="player2">Choose an opponent</label>
  <select name="game[player_2_id]" id="player2">
  <option></option>
  <%= @players.each do |player| %>
    <option value="<%= player.id %>"><%= player.email %></option>
  <% end %>
  </select>
  </div>

  <div class="submit">
    <input type="submit" value="Create game">
  </div>
</form>

app/views/games/show.html.erb
<div class="game group">
  <% if @player2 == current_player%>
    <h3 class="player-name">You are <div class="player-color-info player-black"></div></h3>
  <% else %>
    <h3 class="player-name"><%= @player2.email %></h3>
  <% end %>
  <section id="board-container" 
    class="group" 
    data-game-id="<%= @game.id %>" 
    data-is-observer="<%= !!@observer %>"
    data-player-color="<%= @game.player_2_id == current_player.id ? 'black' : 'white' %>">
    <%= render partial: 'games/board', locals: { game: @game, turn: @turn, errors: @errors } %>
  </section>
  <footer>
  <% if @player1 == current_player%>
    <h3 class="player-name">You are <div class="player-color-info"></div></h3>
  <% else %>
    <h3 class="player-name"><%= @player1.email %></h3>
  <% end %>
  </footer>
</div>
<script src="http://js.pusher.com/2.2/pusher.min.js"></script>
<script>

  $(document).ready(function() {
  var fromRow;
  var toRow;
  var fromCol;
  var toCol;
  var $piece;
  var $fromTile;
  var color;
  var $prevTile;
  var playerColor = $("#board-container").attr("data-player-color");
  var game_id = $("#board-container").attr("data-game-id");

  function rebind() {
  color = $(".board").attr("data-current-turn");
  if (color === playerColor) {
  $(".piece." + color).draggable({})
  $(".piece." + color).addClass("moveable-piece")
  $( ".tile" ).droppable({
    hoverClass: "move-tile",
    accept: '.piece',
    greedy: true,
    drop: function( event, ui ) {
      $(".errors").empty();
      var $tar = $(event.target)

      toRow = $tar.attr('data-row-id')
      toCol = $tar.attr('data-col-id')

      $fromTile.html('');
      $tar.html($piece);
      $piece.removeAttr("style");
      $piece.draggable();
      $.ajax({
        url: '/games/' + game_id,
        type: 'PATCH',
        data: { 'from': [fromRow, fromCol], 
        'to': [toRow, toCol], 
        'color': $piece.attr('data-color'),
        'turn': color },
        success: function(data) {
          console.log(data)
          $("#board-container").html(data);
          rebind();

        }
      })
    }
  });

  $("#board-container").on("mousedown", ".piece." + color, function(event) {
    $piece = $(event.currentTarget);
    $fromTile = $(event.currentTarget).closest("article");
    fromRow = $fromTile.attr('data-row-id');
    fromCol = $fromTile.attr('data-col-id');
  });

  }
  }

  if ($("#board-container").attr("data-is-observer") == "false") {
    rebind();
  }

  Pusher.log = function(message) {
    // console.log(message);
  };

  var pusher = new Pusher("<%= ENV['PUSHER_KEY'] %>");

  var channel = pusher.subscribe("opp-move");

  channel.bind("move", function (data) {
    $("#board-container").html(data);
    rebind();
  });
  
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChessMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if current_player %>
<p class="current-user">logged in as: <%= current_player.email %></p>
<% end %>
<%= button_to('Sign Out', destroy_player_session_url, method: :delete) if player_signed_in? %>
<%= link_to "Back to Games", games_url %>
<%= link_to "New Game", new_game_url %>

<%= yield %>

</body>
</html>